routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/documents/to-sign', 'DocumentController@toSign')->name('toSign');
Route::get('/documents/signed', 'DocumentController@signed')->name('signed');

Route::post('/documents/sign', 'DocumentController@sign')->name('sign');

Route::resource('documents', 'DocumentController');
Route::resource('routes', 'RouteController');

app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class Document extends Model
{
    public function author () {
        return $this->belongsTo(User::class, 'author_id');
    }

    public function routes () {
        return $this->hasMany(Route::class)->orderByDesc('id');
    }

    public function activeRoute () {
        return $this->hasOne(Route::class)->where('signed', false);
    }

    public function users()
    {
        return $this->belongsToMany(User::class, 'routes');
    }

    public function scopeActive (Builder $query, $id) {
        return $query->whereHas('activeRoute', function ($q) use ($id) {
            $q->where('user_id', $id);
        });
    }

    public function signed ($user) {
        return ($this->routes->where('user_id', $user->id)->where('signed', true)->first()) ? true : false;
    }

}

app/Route.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Route extends Model
{

    protected $fillable = [
      'user_id',
      'document_id',
    ];

    public function user () {
        return $this->belongsTo(User::class);
    }

    public function document () {
        return $this->belongsTo(Document::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Builder;


class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function authored () {
        return $this->hasMany(Document::class, 'author_id');
    }

    public function routes () {
        return $this->hasMany(Route::class);
    }

    public function toSign()
    {
        return $this->belongsToMany(Document::class, 'routes')->where('signed', false);
    }

    public function signed()
    {
        return $this->belongsToMany(Document::class, 'routes')->where('signed', true);
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use App\Document;
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Builder;

class DocumentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $path = $request->file('document')->store('documents');

        $document = new Document;
        $document->author_id = auth()->id();
        $document->name = $request->name;
        $document->file = $path;
        $document->save();

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function show(Document $document)
    {
        return view('docs.show', compact('document'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function edit(Document $document)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Document $document)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function destroy(Document $document)
    {
        //
    }

    public function toSign () {

        return view('docs.to-sign');

    }

    public function signed () {

        return view('docs.signed');

    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use PDF;
use Illuminate\Support\Facades\Storage;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**cd ..
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }


}

app/Http/Controllers/RouteController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RouteCreateRequest;
use App\Route;
use App\User;
use Illuminate\Http\Request;

class RouteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param RouteCreateRequest $request
     * @return void
     */
    public function create(RouteCreateRequest $request)
    {

        $user = User::where('email', $request->email)->firstOrFail();
        $route = Route::create([
            'user_id' => $user->id,
            'document_id' => $request->document_id,
        ]);
        $route->save();
        return redirect()->back();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Route  $route
     * @return \Illuminate\Http\Response
     */
    public function show(Route $route)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Route  $route
     * @return \Illuminate\Http\Response
     */
    public function edit(Route $route)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Route  $route
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Route $route)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Route  $route
     * @return \Illuminate\Http\Response
     */
    public function destroy(Route $route)
    {
        //
    }
}

resources/views/docs/create.blade.php
<div class="modal fade" id="addDoc" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Добавить документ</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('documents.store') }}" enctype="multipart/form-data" method="POST">
                    @csrf
                    <div>
                        <input class="form-control mb-3" type="text" name="name" placeholder="Название документа">
                        <input class="form-control-file mb-3" type="file" name="document" id="document">
                    </div>
                    <button class="btn btn-primary">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/docs/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Архив документов</div>

                <div class="card-body">

                    <div class="list-group">
                        @foreach($documents as $item)
                            <a href="{{ route('documents.show', $item) }}" class="list-group-item list-group-item-action flex-column align-items-start">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">{{ $item->author->name }}</h5>
                                    <small>{{  $item->created_at->format('d/m/Y') }}</small>
                                </div>
                                <p class="mb-1">{{ $item->name }}</p>
                                <small>Статус: @if($item->activeRoute->user_id == Auth::user()->id) Ждет вашей подписи @else Подписано 3 из 5 @endif</small>
                            </a>
                        @endforeach
                    </div>

                </div>
            </div>
        </div>
        <div class="col-md-4 mt-3 mt-lg-0">
            <div class="card">
                <div class="card-header">Актуальное</div>

                <div class="card-body">
                    <ul class="list-group">
                        <a href="" class="list-group-item">
                            <li class="d-flex justify-content-between align-items-center">
                                Подписаны мною
                                <span class="badge badge-primary badge-pill">2</span>
                            </li>
                        </a>

                        <a href="" class="list-group-item">
                            <li class="d-flex justify-content-between align-items-center">
                                Ждут вашей подписи
                                <span class="badge badge-primary badge-pill">{{ auth()->user()->waitForYourSign->count() }}</span>
                            </li>
                        </a>


                    </ul>
                    <a href="">
                        <button class="btn btn-outline-primary btn-block mt-3">Архив документов</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/docs/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Документ: {{ $document->name }} от {{  $document->created_at->format('d/m/Y') }} </div>
                    <div class="card-body">
                        <div class="d-flex w-100 justify-content-between">
                            <h3>Маршрут документа</h3>
                            <button class="btn btn-outline-primary" data-toggle="modal" data-target="#addPoint">Добавить точку</button>


                            <!-- Modal -->
                            <div class="modal fade" id="addPoint" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLongTitle">Добавить точку</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <form method="GET" action="{{ route('routes.create') }}">
                                                @csrf
                                                <div class="input-group">
                                                    <input type="hidden" value="{{ $document->id }}" name="document_id">
                                                    <input type="text" name="email" class="form-control" placeholder="email">
                                                    <div class="input-group-append">
                                                        <button class="btn btn-outline-secondary" type="submit">Button</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div class="d-flex w-100">
                            <ul class="timeline">
                                @foreach ($document->routes as $item)

                                    <li>
                                        <div>Должность</div>
                                        <div>ФИО: {{ $item->user->name }} </div>
                                        Статус документа: <span class="text-success">{{ $item->signed ? 'Подписан' : 'На рассмотрении' }}</span>
                                    </li>
                                @endforeach
                            </ul>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">Статус</div>
                    <div class="card-body">
                        <div class="d-flex w-100 h5 border-bottom py-3">Подписи <span class="text-primary ml-auto">3 из 6</span></div>
                        @if($document->activeRoute)
                            @if($document->activeRoute->user_id == Auth::user()->id)
                                <form action="">
                                    @csrf
                                    <a href="">
                                        <button class="btn btn-primary btn-block mt-3">Подписать</button>
                                    </a>
                                </form>

                            @elseif ($document->signed(auth()->user()))
                                <button class="btn btn-success btn-block mt-3" disabled>Вы уже подписали</button>

                            @else
                                <button class="btn btn-secondary btn-block mt-3" disabled>Вы пока не можете подписать</button>
                            @endif
                        @else
                            <div class="my-3">У документа пока нет маршрута...</div>
                            <button class="btn btn-outline-primary btn-block" data-toggle="modal" data-target="#addPoint">Добавить точку</button>


                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/docs/signed.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ isset($heading) ? $heading : 'Документы' }}</div>

                <div class="card-body">
                    <a href=""><button class="btn btn-block btn-outline-primary mb-3">Добавить документ</button></a>
                    <div class="list-group">
                        @foreach(auth()->user()->signed as $item)
                            <a href="{{ route('documents.show', $item) }}" class="list-group-item list-group-item-action flex-column align-items-start">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">{{ $item->author->name }}</h5>
                                    <small>{{  $item->created_at->format('d/m/Y') }}</small>
                                </div>
                                <p class="mb-1">{{ $item->name }}</p>
                                <small>Статус: @if($item->activeRoute->user_id == Auth::user()->id) Ждет вашей подписи @else Подписано 3 из 5 @endif</small>
                            </a>
                        @endforeach
                    </div>

                </div>
            </div>
        </div>
        <div class="col-md-4 mt-3 mt-lg-0">
            <div class="card">
                <div class="card-header">Актуальное</div>

                <div class="card-body">
                    <ul class="list-group">


{{--                        <a href="" class="list-group-item">--}}
{{--                            <li class="d-flex justify-content-between align-items-center">--}}
{{--                                Подписаны мною--}}
{{--                                <span class="badge badge-primary badge-pill">2</span>--}}
{{--                            </li>--}}
{{--                        </a>--}}

{{--                        <a href="" class="list-group-item">--}}
{{--                            <li class="d-flex justify-content-between align-items-center">--}}
{{--                                Ждут вашей подписи--}}
{{--                                <span class="badge badge-primary badge-pill">{{ auth()->user()->waitForYourSign->count() }}</span>--}}
{{--                            </li>--}}
{{--                        </a>--}}


                    </ul>
                    <a href="">
                        <button class="btn btn-outline-primary btn-block mt-3">Архив документов</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/docs/to-sign.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Направленные мне</div>

                <div class="card-body">
                    <a href=""><button class="btn btn-block btn-outline-primary mb-3">Добавить документ</button></a>
                    <div class="list-group">
                        @foreach(auth()->user()->toSign as $item)
                            <a href="{{ route('documents.show', $item) }}" class="list-group-item list-group-item-action flex-column align-items-start">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">{{ $item->author->name }}</h5>
                                    <small>{{  $item->created_at->format('d/m/Y') }}</small>
                                </div>
                                <p class="mb-1">{{ $item->name }}</p>
                                <small>Статус: @if($item->activeRoute->user_id == Auth::user()->id) Ждет вашей подписи @else Подписано 3 из 5 @endif</small>
                            </a>
                        @endforeach
                    </div>

                </div>
            </div>
        </div>
        <div class="col-md-4 mt-3 mt-lg-0">
            <div class="card">
                <div class="card-header">Актуальное</div>

                <div class="card-body">
                    <ul class="list-group">
{{--                        <a href="" class="list-group-item">--}}
{{--                            <li class="d-flex justify-content-between align-items-center">--}}
{{--                                На рассмотрении--}}
{{--                                <span class="badge badge-primary badge-pill">14</span>--}}
{{--                            </li>--}}
{{--                        </a>--}}

{{--                        <a href="" class="list-group-item">--}}
{{--                            <li class="d-flex justify-content-between align-items-center">--}}
{{--                                Подписаны мною--}}
{{--                                <span class="badge badge-primary badge-pill">{{ auth()->user()->signed->count() }}</span>--}}
{{--                            </li>--}}
{{--                        </a>--}}

{{--                        <a href="" class="list-group-item">--}}
{{--                            <li class="d-flex justify-content-between align-items-center">--}}
{{--                                Ждут вашей подписи--}}
{{--                                <span class="badge badge-primary badge-pill">{{ auth()->user()->toSign->count() }}</span>--}}
{{--                            </li>--}}
{{--                        </a>--}}


                    </ul>
                    <a href="">
                        <button class="btn btn-outline-primary btn-block mt-3">Архив документов</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Мои документы</div>

                <div class="card-body">
                    <button class="btn btn-outline-primary btn-block mb-3" data-toggle="modal" data-target="#addDoc">Добавить документ</button>
                    <!-- Modal -->
                    @include('docs.create')

                    <div class="list-group">
                        @foreach(auth()->user()->authored as $item)
                            <a href="{{ route('documents.show', $item) }}" class="list-group-item list-group-item-action flex-column align-items-start">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">{{ $item->author->name }}</h5>
                                    <small>{{  $item->created_at->format('d/m/Y') }}</small>
                                </div>
                                <p class="mb-1">{{ $item->name }}</p>
                                <small>Статус: подписано 3 из 5</small>
                            </a>
                        @endforeach
                    </div>

                </div>
            </div>
        </div>
        <div class="col-md-4 mt-3 mt-lg-0">
            <div class="card">
                <div class="card-header">Актуальное</div>

                <div class="card-body">
                    <ul class="list-group">
{{--                        <a href="" class="list-group-item">--}}
{{--                            <li class="d-flex justify-content-between align-items-center">--}}
{{--                                На рассмотрении--}}
{{--                                <span class="badge badge-primary badge-pill">14</span>--}}
{{--                            </li>--}}
{{--                        </a>--}}

                        <a href="{{ route('signed') }}" class="list-group-item">
                            <li class="d-flex justify-content-between align-items-center">
                                Подписаны мною
                                <span class="badge badge-primary badge-pill">{{ auth()->user()->signed->count() }}</span>
                            </li>
                        </a>

                        <a href="{{ route('toSign') }}" class="list-group-item">
                            <li class="d-flex justify-content-between align-items-center">
                                Направленные вам
                                <span class="badge badge-primary badge-pill">{{ auth()->user()->toSign->count() }}</span>
                            </li>
                        </a>


                    </ul>
                    <a href="">
                        <button class="btn btn-outline-primary btn-block mt-3">Архив документов</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

<script>
    $( document ).ready(function() {
        console.log( "ready!" );
    });
</script>

</html>